# This file was generated by GoReleaser. DO NOT EDIT.
cask "idrac_exporter" do
  version "1.3.3"

  on_macos do
    on_intel do
      sha256 "5f73fa56eb3e9b739e8a6f1c80ed30bea4febdd3e9783d2f52e6f6ec1925a5c6"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "adc0c1d6135669939cbe9568799aa062768cd5336e61acac99c81b129a6f5c6e"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7c016176f0f5d428821eeceeb860daf08d59d20a14af4905b42b21233897fe93"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1f6bafce75bf6eaffbcb07f99bf7812bfc6d0724e86ebab4cb2565437d99c32"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "idrac_exporter"
  desc "Redfish (iDRAC, iLO, XClarity) exporter for Prometheus"
  homepage "https://github.com/fjacquet/idrac_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "idrac_exporter"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/idrac_exporter"
    end
  end

  # No zap stanza required

end
