# This file was generated by GoReleaser. DO NOT EDIT.
cask "idrac_exporter" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "68fa7933dc13ccb9e9a7ae63f839721f2a85a1e798ee88dfb88e9d1cc2f7a1fe"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab513e53d70853f446f11519b767b66f4a00a917e4651040e3b2bdbe1623d18d"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d68b64f48f9c6fcfd3466d0976f9d01057a73160f83a57eac3c1d1f7ae3b5c5f"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cafbbc2483e76d9db87b80a543d01067e5e9be66f89a0b2b44b94b9a26e37ebc"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "idrac_exporter"
  desc "Redfish (iDRAC, iLO, XClarity) exporter for Prometheus"
  homepage "https://github.com/fjacquet/idrac_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "idrac_exporter"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/idrac_exporter"
    end
  end

  # No zap stanza required

end
