# This file was generated by GoReleaser. DO NOT EDIT.
cask "idrac_exporter" do
  version "1.3.2"

  on_macos do
    on_intel do
      sha256 "28d63b74a1e186db3327199f986261e7aa9c1bf4f4228d10dcaf2cc1651f7cfd"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d6e9f879e3379eb094573765703752f0b0f5a1eb95cb858c1c9b71dc384c0eda"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce8da67a39f855122f85a5b2a19b83328402839c46947bfcba423279ddf93479"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "63c0c99aa0aaae5891e50faca8d2e1708f42cdf4eb59fc570380047d2df443ee"
      url "https://github.com/fjacquet/idrac_exporter/releases/download/v#{version}/idrac_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "idrac_exporter"
  desc "Redfish (iDRAC, iLO, XClarity) exporter for Prometheus"
  homepage "https://github.com/fjacquet/idrac_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "idrac_exporter"

  postflight do
    if OS.mac?
      system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/idrac_exporter"
    end
  end

  # No zap stanza required

end
