# This file was generated by GoReleaser. DO NOT EDIT.
cask "nbu_exporter" do
  version "4.1.0"

  on_macos do
    on_intel do
      sha256 "6d1301aaeb768cf52051679fa0921d405b06d9849706f133e9c8afc8f813fbb1"
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v#{version}/nbu_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f59705bd7d373a0731afafa426e95b1d555e23d3452ef06687f25ae630363231"
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v#{version}/nbu_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "nbu_exporter"
  desc "Prometheus exporter for Veritas NetBackup"
  homepage "https://github.com/fjacquet/nbu_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nbu_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nbu_exporter"]
    end
  end

  # No zap stanza required

end
