# This file was generated by GoReleaser. DO NOT EDIT.
cask "nbu_exporter" do
  version "4.0.1"

  on_macos do
    on_intel do
      sha256 "1da0623d9af2839a90af64f274b35e0e3f52a3e5065506f8a54533ec246da391"
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v#{version}/nbu_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f94aba409481214d2890fd13fd117a0599f63d607615ba28ea9f953f316e895"
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v#{version}/nbu_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "nbu_exporter"
  desc "Prometheus exporter for Veritas NetBackup"
  homepage "https://github.com/fjacquet/nbu_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nbu_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nbu_exporter"]
    end
  end

  # No zap stanza required

end
