# This file was generated by GoReleaser. DO NOT EDIT.
cask "nbu_exporter" do
  version "4.0.3"

  on_macos do
    on_intel do
      sha256 "7ce0a5bb429cc7dcd42aa7dfaab3bc8d98019a71e8d70f64af41dc4dc9c09d02"
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v#{version}/nbu_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "82e39d26d815af791edbbcbe2f16efde052ed40e08269bf083777382bd8d2062"
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v#{version}/nbu_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "nbu_exporter"
  desc "Prometheus exporter for Veritas NetBackup"
  homepage "https://github.com/fjacquet/nbu_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nbu_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nbu_exporter"]
    end
  end

  # No zap stanza required

end
