# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsr_exporter" do
  version "0.12.4"

  on_macos do
    on_intel do
      sha256 "521097efe6e7589239278bfc6e89b7d9eaeb443be39dfcd82c27c8b2387cdd29"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "579750f371f261a3c1a3682532bf89a531eca88ec04c53afe68eed0401e37617"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76624f1fa9c0070bad4b5828449349689454211ae951f3d2b077e18d0edca61f"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b743487a8237e354145b3655b41e63f47fef9da985b220cd2333372b149ed3c6"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nsr_exporter"
  desc "Prometheus + OTLP exporter for Dell EMC NetWorker"
  homepage "https://github.com/fjacquet/nsr_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsr_exporter"

  postflight do
    if OS.mac?
      system "xattr", "-d", "com.apple.quarantine", "#{staged_path}/nsr_exporter" rescue nil
    end
  end

  # No zap stanza required

end
