# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsr_exporter" do
  version "0.15.1"

  on_macos do
    on_intel do
      sha256 "034f234d9aef60235ee389a0c239f9c464220d269b58334572598ecbcd2937f3"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2ce896995c53aef808bfa01015cd84cda45f6b181dec8032b8e0df64470f4c1"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5fa77ad2c7e50955f9fce554dcc9f76e054f8754286918837bc684cf0beeb5b3"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3b0fef81a642b7110d8ba8c2d00fa2a6eee9e6a549b1e64d09265ce33610da65"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nsr_exporter"
  desc "Prometheus + OTLP exporter for Dell EMC NetWorker"
  homepage "https://github.com/fjacquet/nsr_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsr_exporter"

  postflight do
    if OS.mac?
      system "xattr", "-d", "com.apple.quarantine", "#{staged_path}/nsr_exporter" rescue nil
    end
  end

  # No zap stanza required

end
