# This file was generated by GoReleaser. DO NOT EDIT.
cask "nsr_exporter" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "5453c85863bf76c433ce7d4042eedc731016ad971b220079cd4eb75292b675ca"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "80c202de1066939d5adacd6534fd157fd9cf5593750ee45d6cfc2edfed4ce6f3"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2befcb6d2f14077c831e0793036ef3f060b8f086ca0320868f2c07195510cfc3"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1239bf6fc39d4f39ba223b0590cabece080d9a818f9567285b417fac232fa9c1"
      url "https://github.com/fjacquet/nsr_exporter/releases/download/v#{version}/nsr_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nsr_exporter"
  desc "Prometheus + OTLP exporter for Dell EMC NetWorker"
  homepage "https://github.com/fjacquet/nsr_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nsr_exporter"

  postflight do
    if OS.mac?
      system "xattr", "-d", "com.apple.quarantine", "#{staged_path}/nsr_exporter" rescue nil
    end
  end

  # No zap stanza required

end
