# This file was generated by GoReleaser. DO NOT EDIT.
cask "obs_exporter" do
  version "2.5.1"

  on_macos do
    on_intel do
      sha256 "66504af1f63bad5afd16911e01193e8d841351f3ac11d6c49ea0d9ec2f6279d2"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79bd058fafd75438cfbc5ad447e2a1712f0876aca14f012df57c907abd1096ab"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e59e019b3dbfff84e2269074880ee21e29d3641f85d3fc019c2f4e34b3b1f59"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a2c15fb49c3540383838a6f9478aaf7dba19ad6ad96eebd5254bf86aa80ed932"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "obs_exporter"
  desc "Prometheus + OTLP exporter for Dell EMC ECS / ObjectScale"
  homepage "https://github.com/fjacquet/obs_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obs_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/obs_exporter"]
    end
  end

  # No zap stanza required

end
