# This file was generated by GoReleaser. DO NOT EDIT.
cask "obs_exporter" do
  version "2.7.0"

  on_macos do
    on_intel do
      sha256 "fc16aa77a112f92a5e86c3f67bb9ec5b27ea0beee24b8649a22e097b696f3c9d"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b5fd39565b17c8527200056562295dda71ff86100d342b2a83d0529202296ad"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ac133ab7824d3fc10e2dffb50ec4eda432beaeb6a2f541ca164d2e7f11125ea"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "20ab81dd5e8f254a766bb1fc07a882583c6ceceeb934b1af569044c4e50db644"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "obs_exporter"
  desc "Prometheus + OTLP exporter for Dell EMC ECS / ObjectScale"
  homepage "https://github.com/fjacquet/obs_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obs_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/obs_exporter"]
    end
  end

  # No zap stanza required

end
