# This file was generated by GoReleaser. DO NOT EDIT.
cask "obs_exporter" do
  version "3.8.1"

  on_macos do
    on_intel do
      sha256 "dd8a50589663817542556fa110bd6d024ee6a197bb14e1e8d45a5846119867a6"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "234a35a67390db29a945efb4815563fdce8c9e48dcc0d8bfc64f5a8099bc656d"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "52bd4e8ce531037454d6d0329e4c33211f9a78789ce8655691af0266ac361676"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc733d233c23474d8370aff56608844093ce876c5b59b7e3126f0ba166969cd7"
      url "https://github.com/fjacquet/obs_exporter/releases/download/v#{version}/obs_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "obs_exporter"
  desc "Prometheus + OTLP exporter for Dell EMC ECS / ObjectScale"
  homepage "https://github.com/fjacquet/obs_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "obs_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/obs_exporter"]
    end
  end

  # No zap stanza required

end
