# This file was generated by GoReleaser. DO NOT EDIT.
cask "pflex_exporter" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "d443e16f234683eb2a4bf9957b01e2844637677666b4bac4a544200ea136ad1c"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4ea9eb406c643e4784e38b143eb4b693e5cd45ff024ac80c7246d55197c13799"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d03b6a93ce405a49cf2d012a1d8ae0df8aba2a7fe3f90934c62b733e1ebe5c13"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b87ebc6a5b5d66647ea700d325771858e80c6f38e60e85d6d9237f9bed921b81"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pflex_exporter"
  desc "Prometheus + OTLP exporter for Dell PowerFlex (Gen1 & Gen2)"
  homepage "https://github.com/fjacquet/pflex_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pflex_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pflex_exporter"]
    end
  end

  # No zap stanza required

end
