# This file was generated by GoReleaser. DO NOT EDIT.
cask "pflex_exporter" do
  version "0.6.4"

  on_macos do
    on_intel do
      sha256 "75c286b8ce081a4941254a77b65c39216c4e4e9a2261b912358e914ea8671282"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93d22b63320817ed437a7a73c2237fb75c128544cf426178a69803bbabbfe41f"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f30d59ee0bf7c2b131d08caed8c2b6b3efce4388dc787008c9231b03ab3bedf3"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7cec6714ce4e5d0f1e529d685fc6a05ec80dfc72d9fca5d4c958ee1b46689028"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pflex_exporter"
  desc "Prometheus + OTLP exporter for Dell PowerFlex (Gen1 & Gen2)"
  homepage "https://github.com/fjacquet/pflex_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pflex_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pflex_exporter"]
    end
  end

  # No zap stanza required

end
