# This file was generated by GoReleaser. DO NOT EDIT.
cask "pflex_exporter" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "07bfc89a7ab5518e8c1265c104a653987e063a04a57b9b9a874e2a2a7f499a3f"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "48970aedb056795a19286e8817ba28245a811449817089163ff3e68de81c3eea"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "309c65dc2e31dc4a66a381a5cb7cc1c48adc7df59e71c7618a1f3579c2228488"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ad66f0bad1d526ec570ba360c289b1d0e10bcc77299f3ed498267daa5c733849"
      url "https://github.com/fjacquet/pflex_exporter/releases/download/v#{version}/pflex_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pflex_exporter"
  desc "Prometheus + OTLP exporter for Dell PowerFlex (Gen1 & Gen2)"
  homepage "https://github.com/fjacquet/pflex_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pflex_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pflex_exporter"]
    end
  end

  # No zap stanza required

end
