# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmax_exporter" do
  version "0.5.6"

  on_macos do
    on_intel do
      sha256 "d1f0c0c493dac6bd33393b86bad0d29b623b21cf44cfb19c0d446b08d723335d"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "bf609d05a9e9c67d997d6a8835696d6feabe0bff0cabc9f2e290881e9d8aa98f"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7b0309f928ae6284c5a928d178dd9af808832c02533b241a093f1112f8a7e16f"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "779514783f30a19c0ae21c978ef07490c3fcf2324d2fdd062cc84b33c81e4f65"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pmax_exporter"
  desc "Prometheus + OTLP exporter for Dell PowerMax"
  homepage "https://github.com/fjacquet/pmax_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmax_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmax_exporter"]
    end
  end

  # No zap stanza required

end
