# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmax_exporter" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "27737f10c5f629947b31b845410b825d82aaaff8be59cfc684a409e2fe868338"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d45078c7993c29d8fe74f387375529be115b139fdd84f878b4f0aeafb042521"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "155a59227315390c8ebf1c1cf822debcd0320f50505f90b224d618aedaa02503"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bcb07d066f905cb53919fac71ca6e1fb20df4e5ef1e9bad43e904a9bd7546a5a"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pmax_exporter"
  desc "Prometheus + OTLP exporter for Dell PowerMax"
  homepage "https://github.com/fjacquet/pmax_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmax_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmax_exporter"]
    end
  end

  # No zap stanza required

end
