# This file was generated by GoReleaser. DO NOT EDIT.
cask "pmax_exporter" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "393e20bf5977df010515853f9e06033b360237661b80d01064132551c5d2146c"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0e2451e10b71c2f445b1a51d716e0380dfe16b184b740bdd7d072a35203cb5d"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "980ff576fe32264cb045c7cdef068a32db23a80747afb6b8f97c2c41340de006"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "67cbf493e8cb5ee128b06ffd19c893cdf120a10cc1ca4bca246a46bb17f57307"
      url "https://github.com/fjacquet/pmax_exporter/releases/download/v#{version}/pmax_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pmax_exporter"
  desc "Prometheus + OTLP exporter for Dell PowerMax"
  homepage "https://github.com/fjacquet/pmax_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pmax_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pmax_exporter"]
    end
  end

  # No zap stanza required

end
