# This file was generated by GoReleaser. DO NOT EDIT.
cask "ppdd_exporter" do
  name "ppdd_exporter"
  desc "Prometheus exporter for Dell PowerProtect DD"
  homepage "https://github.com/fjacquet/ppdd_exporter"
  version "0.8.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ppdd_exporter"

  on_macos do
    on_intel do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_darwin_amd64.tar.gz"
      sha256 "18a71e7014fd791aa1d9b5f7fe4b055f4f3a2b243da5033835415b8462a8ffe7"
    end
    on_arm do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_darwin_arm64.tar.gz"
      sha256 "b078342aea6023d406396058e398efaf273e3ba846dc4bdc3d94d21c35558cdb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_linux_amd64.tar.gz"
      sha256 "e3cf467122509f6a5d1a2de3c5a5db92d4806f6244b11b9c29154ffbe996f9d4"
    end
    on_arm do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_linux_arm64.tar.gz"
      sha256 "fcb625723a099e1a95621b380e2db9ec2e7e22c0216d259f9d3dd8a0ce1b048e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ppdd_exporter"]
    end
  end

  # No zap stanza required
end
