# This file was generated by GoReleaser. DO NOT EDIT.
cask "ppdd_exporter" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "8abe72f001e6fa1ed7e062cff2b80c6d67825bd3a883e4448579b5a49271f338"
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "469d5106b648f1aa6b1b8787f1770819caa6d1dad5fd1fd528ba7a2566d580f8"
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d7288611061055359483a2e1c9ecb94302f642043b53673677d3ad30f0a187aa"
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "139ae5d20a5d64a6a9e8b59726551ad71041718e9371e27bfb64cf614c22d946"
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ppdd_exporter"
  desc "Prometheus exporter for Dell PowerProtect DD"
  homepage "https://github.com/fjacquet/ppdd_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ppdd_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ppdd_exporter"]
    end
  end

  # No zap stanza required

end
