# This file was generated by GoReleaser. DO NOT EDIT.
cask "ppdd_exporter" do
  name "ppdd_exporter"
  desc "Prometheus exporter for Dell PowerProtect DD"
  homepage "https://github.com/fjacquet/ppdd_exporter"
  version "0.8.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ppdd_exporter"

  on_macos do
    on_intel do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_darwin_amd64.tar.gz"
      sha256 "4feea53f89a457c139084c9ecbf8c897e6392434267e67f51a2e9354e12bff4d"
    end
    on_arm do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_darwin_arm64.tar.gz"
      sha256 "afc55776dbd6b7f71dbc266f4aeb9c1a8881f427d9435db3f0a2ac6e65b3c526"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_linux_amd64.tar.gz"
      sha256 "a3d1b6fcc9a4077082d5b03fe6fc2d3ccdf19605364f2255f311b1e2a6c7ab32"
    end
    on_arm do
      url "https://github.com/fjacquet/ppdd_exporter/releases/download/v#{version}/ppdd_exporter_#{version}_linux_arm64.tar.gz"
      sha256 "16034393f8fa896fc9920ca735b68bce9a810778cfa7048b7361470d6585a355"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ppdd_exporter"]
    end
  end

  # No zap stanza required
end
