# This file was generated by GoReleaser. DO NOT EDIT.
cask "pscale_exporter" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "d9fd3a4880ea1eddaa903b6e12e49139d0afab2878046e1b71a2cbdf110d56e2"
      url "https://github.com/fjacquet/pscale_exporter/releases/download/v#{version}/pscale_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c55b8c3a272f4e0fbf8c62b38cc5c219be617470fa13b695bea8ae716c7a89b5"
      url "https://github.com/fjacquet/pscale_exporter/releases/download/v#{version}/pscale_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "pscale_exporter"
  desc "Prometheus & OTLP exporter for Dell PowerScale (OneFS)"
  homepage "https://github.com/fjacquet/pscale_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pscale_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pscale_exporter"]
    end
  end

  # No zap stanza required

end
