# This file was generated by GoReleaser. DO NOT EDIT.
cask "pscale_exporter" do
  version "0.12.1"

  on_macos do
    on_intel do
      sha256 "4b1016a151b299b1ec13f02a3d573fead65574252ec16582a87a584a78ae51e0"
      url "https://github.com/fjacquet/pscale_exporter/releases/download/v#{version}/pscale_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "71215957bebf0e259d465f9759e98f1b02d18f910980115fe4b1a91987b6b4cd"
      url "https://github.com/fjacquet/pscale_exporter/releases/download/v#{version}/pscale_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "pscale_exporter"
  desc "Prometheus & OTLP exporter for Dell PowerScale (OneFS)"
  homepage "https://github.com/fjacquet/pscale_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pscale_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pscale_exporter"]
    end
  end

  # No zap stanza required

end
