# This file was generated by GoReleaser. DO NOT EDIT.
cask "pscale_exporter" do
  version "0.19.3"

  on_macos do
    on_arm do
      sha256 "031d1aa09c88b98ce9ab9e406be086f0a9cd70a2fe0fdf6b43c30565de6ea404"
      url "https://github.com/fjacquet/pscale_exporter/releases/download/v#{version}/pscale_exporter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f16d9847ca897a4f625cc781975244538b55548025bfd68580cd58569fd1e7a0"
      url "https://github.com/fjacquet/pscale_exporter/releases/download/v#{version}/pscale_exporter_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "pscale_exporter"
  desc "Prometheus & OTLP exporter for Dell PowerScale (OneFS)"
  homepage "https://github.com/fjacquet/pscale_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pscale_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pscale_exporter"]
    end
  end

  # No zap stanza required
end
