# This file was generated by GoReleaser. DO NOT EDIT.
cask "pstore_exporter" do
  version "2.3.2"

  on_macos do
    on_intel do
      sha256 "903a47fc3366d3de7bcfb393434946b3c68f36a33805c8a2ecfd83fc9db98438"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "100eec44e37d0a7a76131a0f4424172d7a2cb8cf1f63c8202fbb169110a3f462"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0523fe41ee5cddebf54ea139633faef4b97f871db7fa367d505c023a77acb27"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "136fc7bff2dee308f04b2a5785c2f053bc9168770d7dd6c9e6605458dcd7ee42"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pstore_exporter"
  desc "Dell PowerStore Prometheus + OTLP exporter"
  homepage "https://github.com/fjacquet/pstore_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pstore_exporter"

  # No zap stanza required

end
