# This file was generated by GoReleaser. DO NOT EDIT.
cask "pstore_exporter" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b0618df7cae87c6103b00a0ac991786f31218ea26841c8fb2cd163e67278e6ca"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f941268ea98fc40209c93925f873c597e9c1be9026443424ebf5d32b9c236387"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "43e4b4d0e5676c052657cd30f0525d74d3c246d5659d5bd17e573724fc862c4e"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b1511aa88fb763afd0c907422a3703d5180bdcb4a1115a58244a0e65d87ace9"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pstore_exporter"
  desc "Dell PowerStore Prometheus + OTLP exporter"
  homepage "https://github.com/fjacquet/pstore_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pstore_exporter"

  # No zap stanza required

end
