# This file was generated by GoReleaser. DO NOT EDIT.
cask "pstore_exporter" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "836debfc4f020a5e69b1a0eb4632908bd11e27309f66447eee9551b8d21e230c"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcf7ce33690609b564fdbc9acf043a351d7808615b629c42b1f2b12e492a73fd"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec1761c4684f3a6bab48ea699926352e465e6f170c899c814341b9d27c1d195f"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c361d8f777e0b5dd21f90d0c10e97939be971049fd9a06c08bd52037591ccbc1"
      url "https://github.com/fjacquet/pstore_exporter/releases/download/v#{version}/pstore_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pstore_exporter"
  desc "Dell PowerStore Prometheus + OTLP exporter"
  homepage "https://github.com/fjacquet/pstore_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pstore_exporter"

  # No zap stanza required

end
