# This file was generated by GoReleaser. DO NOT EDIT.
cask "pve_exporter" do
  version "0.7.2"

  on_macos do
    on_intel do
      sha256 "45af34ef4e6ee727e11491a55801b1509d2f7873fb273d6ac09119584d803759"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "42952da5551b4002e15260bdef9084e29f4f5ae2df76ec89b99a4c7047dc0c37"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ad4e2a96fb24527670b237f10183f418e6d3676dd4c6b54e84f2d55a9af83e06"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8bd86cf1d1a142a67b8f663e12625d4fa7f9869da1613a315150038f9b11952"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pve_exporter"
  desc "Prometheus exporter for Proxmox VE (pve_exporter)"
  homepage "https://github.com/fjacquet/pve_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pve_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pve_exporter"]
    end
  end

  # No zap stanza required

end
