# This file was generated by GoReleaser. DO NOT EDIT.
cask "pve_exporter" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "7d2fbc17a062f24b83740851c48d210a4224888cb73dac19a8354b2465ae8743"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6bb6648093ff0934a47028843da51d9145f537975189349623bb414956bb8b8a"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "04dfdc63b8117ceddb00b9e21510c70bc65984d28bf433a7899b96dab86225be"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "596900bd2d08bb4753b96005f2eb84be95aee0b35aaa2526d627a4f3c8c402d5"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pve_exporter"
  desc "Prometheus exporter for Proxmox VE (pve_exporter)"
  homepage "https://github.com/fjacquet/pve_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pve_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pve_exporter"]
    end
  end

  # No zap stanza required

end
