# This file was generated by GoReleaser. DO NOT EDIT.
cask "pve_exporter" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "88fc987c74bf3e3187bb18351f13a1360520f400995c037f37a164df39a37ac9"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55a842397c41d88894a49fa4278c93ff3335a2fb7e29cb176f7db761af507d01"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "214f26919eb5388785aec049654eeaa8e8576a1305a07e2e3ffe1d31e91b3b82"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d1f73ba056bcd4c3267e2ad2ecae2372c80b4f5c689afbabd55f0acd40e44df"
      url "https://github.com/fjacquet/pve_exporter/releases/download/v#{version}/pve_exporter_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pve_exporter"
  desc "Prometheus exporter for Proxmox VE (pve_exporter)"
  homepage "https://github.com/fjacquet/pve_exporter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pve_exporter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pve_exporter"]
    end
  end

  # No zap stanza required

end
