# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CamtCsv < Formula
  desc "Convert financial statements (CAMT.053 XML, PDF, Revolut CSV, Selma CSV) to standardized CSV with AI-powered categorization"
  homepage "https://github.com/fjacquet/camt-csv"
  version "2.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fjacquet/camt-csv/releases/download/v2.5.0/camt-csv_2.5.0_darwin_amd64.tar.gz"
      sha256 "f62a780bfffed1a3dec601ee2c50670f807b788d68f28fdad3138b23ffb44378"

      def install
        bin.install "camt-csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fjacquet/camt-csv/releases/download/v2.5.0/camt-csv_2.5.0_darwin_arm64.tar.gz"
      sha256 "405e32e06ceead3c3da82301d821e53cc61d0ea4c4bcdbe05c97984b9b7c6f2b"

      def install
        bin.install "camt-csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fjacquet/camt-csv/releases/download/v2.5.0/camt-csv_2.5.0_linux_amd64.tar.gz"
        sha256 "7b8604f5be7d176c793343c131998d42bb6fb730dbad53621edba33716194e8e"

        def install
          bin.install "camt-csv"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fjacquet/camt-csv/releases/download/v2.5.0/camt-csv_2.5.0_linux_arm64.tar.gz"
        sha256 "b9d27598b351c7411dfbb9795d474be59322ace8bfb87ce8716088449a4b7264"

        def install
          bin.install "camt-csv"
        end
      end
    end
  end

  test do
    system "#{bin}/camt-csv", "--version"
  end
end
