# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CamtCsv < Formula
  desc "Convert financial statements (CAMT.053 XML, PDF, Revolut CSV, Selma CSV) to standardized CSV with AI-powered categorization"
  homepage "https://github.com/fjacquet/camt-csv"
  version "2.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fjacquet/camt-csv/releases/download/v2.2.0/camt-csv_2.2.0_darwin_amd64.tar.gz"
      sha256 "b88110ee5230da686e52d58aa561228b412aeefb33b82f464c49193905cc8fea"

      def install
        bin.install "camt-csv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fjacquet/camt-csv/releases/download/v2.2.0/camt-csv_2.2.0_darwin_arm64.tar.gz"
      sha256 "9c4a2cfa85881066e447dafb58fd44c2e4afb7fd828b86984551c2a0b6f92177"

      def install
        bin.install "camt-csv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjacquet/camt-csv/releases/download/v2.2.0/camt-csv_2.2.0_linux_amd64.tar.gz"
      sha256 "b0acc0ad9de22bbba323e4ed3e9f2af018d8ff3e1ebea3c8431e422aad30fa5b"
      def install
        bin.install "camt-csv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjacquet/camt-csv/releases/download/v2.2.0/camt-csv_2.2.0_linux_arm64.tar.gz"
      sha256 "45bfd04440f957939f36e1023b205af0dfc98bce9386f4daa48e5a649bf66021"
      def install
        bin.install "camt-csv"
      end
    end
  end

  test do
    system "#{bin}/camt-csv", "--version"
  end
end
