# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NbuExporter < Formula
  desc "Prometheus exporter for Veritas NetBackup"
  homepage "https://github.com/fjacquet/nbu_exporter"
  version "2.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v2.3.1/nbu_exporter_2.3.1_darwin_amd64.tar.gz"
      sha256 "88ef636f25fae1bea0d4ae6b45beb2af95f413d11636ffa26cfecffe6a8ea532"

      def install
        bin.install "nbu_exporter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v2.3.1/nbu_exporter_2.3.1_darwin_arm64.tar.gz"
      sha256 "0a3befbaa7c74f6b881dc1df87d14c29130d96423b725264f1f2e4857b0cd908"

      def install
        bin.install "nbu_exporter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v2.3.1/nbu_exporter_2.3.1_linux_amd64.tar.gz"
      sha256 "58653216369d4343c3236a37db88e73b5a8573345eb4bbb8aa0c9c7090386513"
      def install
        bin.install "nbu_exporter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fjacquet/nbu_exporter/releases/download/v2.3.1/nbu_exporter_2.3.1_linux_arm64.tar.gz"
      sha256 "1f6e80938e97047c795ed0e0b02374ee5858ff1c4b6eac181c429479f0304b7d"
      def install
        bin.install "nbu_exporter"
      end
    end
  end

  test do
    system "#{bin}/nbu_exporter", "--version"
  end
end
